# Generated by Django 5.2.2 on 2025-06-11 10:01

import django_jalali.db.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('familyloanclub', '0002_accessrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birth_year',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='referrer_name',
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ تولد (شمسی)'),
        ),
        migrations.AddField(
            model_name='profile',
            name='referrer_phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
